[
  {
    name: "Chile",
    topLevelDomain: [".cl"],
    alpha2Code: "CL",
    alpha3Code: "CHL",
    callingCodes: ["56"],
    capital: "Santiago",
    altSpellings: ["CL", "Republic of Chile", "Rep\u00fablica de Chile"],
    region: "Americas",
  },
  {
    name: "China",
    topLevelDomain: [".cn"],
    alpha2Code: "CN",
    alpha3Code: "CHN",
    callingCodes: ["86"],
    capital: "Beijing",
    altSpellings: [
      "CN",
      "Zh\u014dnggu\u00f3",
      "Zhongguo",
      "Zhonghua",
      "People\u0027s Republic of China",
      "\u4e2d\u534e\u4eba\u6c11\u5171\u548c\u56fd",
      "Zh\u014dnghu\u00e1 R\u00e9nm\u00edn G\u00f2ngh\u00e9gu\u00f3",
    ],
    region: "Asia",
  },
];
